language: node_js
node_js:
  - "7"
script:
  - echo "Deploy!!"
install:
  - npm install -g firebase-tools gulp
  - npm install
after_success:
  - gulp build
  - firebase deployâ€Š- project jamesehlycom - token $FIREBASE_TOKEN